#!/usr/bin/env python
import yum

def makecache():
    base = yum.YumBase()
    base.doConfigSetup(fn = '/etc/fedoracommunity/yum_cache.conf')

    print base.repos.findRepos('*') 
    try:
        for repo in base.repos.findRepos('*'):
            repo.metadata_expire = 0
            repo.mdpolicy = "group:all"
        base.doRepoSetup()
        base.repos.doSetup()
        for repo in base.repos.listEnabled():
            repo.repoXML

        # These convert the downloaded data into usable data,
        # we can't remove them until *LoadRepo() can do:
        # 1. Download a .sqlite.bz2 and convert to .sqlite
        # 2. Download a .xml.gz and convert to .xml.gz.sqlite
        base.repos.populateSack(mdtype='metadata', cacheonly=1)
        base.repos.populateSack(mdtype='filelists', cacheonly=1)
        base.repos.populateSack(mdtype='otherdata', cacheonly=1)


    except yum.Errors.YumBaseError, e:
        return 1, [str(e)]

makecache()

