#!/bin/bash -x
# Update fedoracommunity dev instance. This command must be run on our puppet
# server in Fedora Infrastructure.

RELEASE=$1
REVISION=$2
DIST=el6
REPO=/mnt/fedora/app/fi-repo/testing/6/
MINION=community01.dev.phx2.fedoraproject.org

rpmsign --resign ~/fcomm/fedoracommunity-$RELEASE-$REVISION.$DIST.{src,noarch}.rpm
sudo cp ~/fcomm/fedoracommunity-$RELEASE-$REVISION.$DIST.src.rpm $REPO/SRPMS/
sudo cp ~/fcomm/fedoracommunity-$RELEASE-$REVISION.$DIST.noarch.rpm $REPO/x86_64/
sudo createrepo --update $REPO/x86_64/
sudo createrepo --update $REPO/SRPMS
sudo func-command --host=$MINION "yum clean metadata"
sudo func-command --host=$MINION "yum update -y fedoracommunity moksha"
sudo func-command --host=$MINION "/usr/local/bin/run-puppet nowait"
sudo func-command --host=$MINION "apachectl graceful"
curl http://$MINION/packages/
