from urlhandler import URLHandler
from kojiurlhandler import KojiURLHandler
from bodhiurlhandler import BodhiURLHandler
from pkgdburlhandler import PkgDBURLHandler
from bugsurlhandler import BugsURLHandler
